name: CI

on: repository_dispatch

jobs:
  test-dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo triggered by another ,
          echo test
